### ISSUE TITLE
Non-IRC chat references

### ISSUE THREAD

**Issue by jaywink** [mozilla/contribute.json#106]
Currently the schema has in the `participate` section both `irc` and `irc-contacts`.

As per [this announcement](https://discourse.mozilla.org/t/synchronous-messaging-at-mozilla-the-decision/50620), IRC is being replaced inside Mozilla with Matrix. This will make it impossible for Mozilla projects to satisfy the demands of [the observatory](https://infosec.mozilla.org/guidelines/web_security#contributejson) which demands an IRC channel and contacts.

The easiest would be to just add `matrix` and `matrix-contacts` in a similar fashion, under `participate`, for example:

```
"participate": {
  "matrix": "#matrix:matrix.org",
  "matrix-contacts": [
    "@someaccount:matrix.org",
    "@someaccount:mozilla.org"
  ],
}
```

However, possibly a more future proof way would be to introduce an array of chat rooms as objects? Something like this, an example for the Matrix project:

```
"participate": {
  "chat": [
    {
      "location": "irc://chat.freenode.net/#matrix",
      "contacts": [
        "someaccount1",
        "someaccount2"
      ]
    },
    {
      "location": "matrix:room/matrix:matrix.org",
      "contacts": [
        "@someaccount1:matrix.org",
        "@someaccount2:mozilla.org"
      ]
    }
  ]
}
```

Not entirely sure what the keys would be. The Matrix URI scheme proposal is based on [MSC2312](https://github.com/matrix-org/matrix-doc/pull/2312) which is yet to be accepted.

Opening for discussion, happy to PR something as well if there is consensus.

**Comment by pmac** [comment]
I like the 2nd option a lot. Even if we don't use a chat-specific URI I think it'd still be useful to give a direct https link to the room where possible, like with chat.m.o.

**Comment by peterbe** [comment]
A much simpler format would be:

```json
"participate": {
  "chat": "#matrix:matrix.org",
  "chat-contacts": ["peterbe", "pmac"]
}
```

Then it can work for any team no matter what they use. If they use Slack, IRC, or Matrix, it's just a URL. 

Another option to consider is this alternative:

```json
"participate": {
  "chat": {
      "url": "#matrix:matrix.org",
      "contacts": ["peterbe", "pmac"]
  }
}
```

This latter is like your latter suggestion. But simpler.

**Comment by peterbe** [comment]
@mathjazz Can you please help out here?

**Comment by mathjazz** [comment]
I wonder if there's need for `chat` to be a list - do projects use more than one chat platform?

In Pontoon we basically followed the first example by @peterbe and linked to c.m.o:
https://github.com/mozilla/pontoon/blob/master/contribute.json#L11

I like his 2nd example even better and would be happy to update if it becomes part of the schema. :)

**Comment by jaywink** [comment]
IMHO having a primary chat link sounds ok. And making `chat` an object IMHO makes more sense and is more future proof.

> "contacts": ["peterbe", "pmac"]

For IRC or some other platforms, this works fine. But for Matrix, the list should contain full mxid's, ie for example `["@peterbe:mozilla.org", "@pmac:mozilla.org"]`, should those users be on the Mozilla server in this case. But this is probably not something that belongs in the contribute.json specification itself :)

So possibly this kind of schema change?

```
  "chat": {
    "type": "object",
    "properties": {
      "url": {
        "type": "string"
      },
      "contacts": {
        "type": "array"
      }
    },
    "required": [
      "url",
      "contacts"
    ]
  }
```

**Comment by peterbe** [comment]
The only thing I don't like is that `contacts` is required. I've been on projects where there is a chat place but there isn't one or two individuals to single out. Attempting to maintain that list, since people come and go, feels like a burden. 

So, I'd love to see that as a PR but with:
```json
"required": [
      "url"
    ]
```

**Comment by julienw** [comment]
Sorry I missed the action here :-)
Any reason why `chat` isn't an array after all? We can imagine projects to be on several channels, one being the primary (eg: chatmo) but others also existing (devtools is on discourse too for example).

Also some "standard" guidance about how to specify a matrix room would be super useful!

What do you think? Should we reopen here or should I file another issue?

**Comment by jaywink** [comment]
> Also some "standard" guidance about how to specify a matrix room would be super useful!

This is indeed a tricky one. I was going to propose using the `matrix://` URI scheme, but it's [not yet accepted](https://github.com/matrix-org/matrix-doc/pull/2312). Until that happens, there isn't a good way to link to a Matrix room. Possibly for now it would be best to just suggest listing the room alias ie `#room:domain.tld` instead of an URI?

**Comment by peterbe** [comment]
> Sorry I missed the action here :-)
> Any reason why `chat` isn't an array after all? We can imagine projects to be on several channels, one being the primary (eg: chatmo) but others also existing (devtools is on discourse too for example). So maybe this could be an array of objects, the first one is the primary implicitely, or there's an explicit `primary: true` property on one of them.
> 
> Also some "standard" guidance about how to specify a matrix room would be super useful!
> 
> What do you think? Should we reopen here or should I file another issue?

I think there's a conflict between simplicity and flexibility. 
Making it a simple object instead of a list/array does make it "dumber" which has its own benefits. 
For it's definitely counter to teams where they have multiple chat rooms(*). 

Perhaps it should have be a list/array from the start. Ah well. 

Is it possible to edit the JSON Schema so it can be an object or a list of said objects? Would that help? I.e. not `urlS` but `chatS` instead. Or is it too late?

(*) A lot of teams have multiple chat rooms but there's usually one that is more "primary" than the others. Especially in terms of where they'd expect new/visitors to come to first.

**Comment by openjck** [comment]
Just reading this now. It doesn't sound like there was agreement on a standardized way to point to a Matrix channel from contribute.json. Is that correct? If so, I can open another issue about that if you'd like.

**Comment by openjck** [comment]
I think the challenge I'm having right now is that there's no standardized URL for a Matrix channel, given its distributed nature, and the matrix:// protocol is not yet supported as mentioned in [this comment](https://github.com/mozilla/contribute.json/issues/106#issuecomment-617956451).

I guess a link to chat.mozilla.com, e.g. https://chat.mozilla.org/#/room/#public-data:mozilla.org would work fine, although matrix:// might be better when it's supported.
