### ISSUE TITLE
participate->home is hard to make required

### ISSUE THREAD

**Issue by peterbe** [mozilla/contribute.json#2]
Many of my projects that I would welcome contributions on (from staff or non-staff) don't even have a wiki page. Usually there's the github page or the docs page that I'd send people to.

The few projects I do have a wiki on are usually out of date. 

In fact, I have projects that would welcome some contributions that don't even have docs. E.g. github.com/mozilla/airmozilla doesn't have docs. 

Can we make the whole `participate` optional?

**Comment by Osmose** [comment]
After having written about 9 `contribute.json` files thusfar, I agree that `home` being required in `participate` is rough. `docs` is easy to fill in but `home` is a challenge.

**Comment by pmclanahan** [comment]
Let's make some more things optional then, but keep the suggested names so that we get consistency when they're provided. Good?
