### ISSUE TITLE
Make clear how to use this as a site owner

### ISSUE THREAD

**Issue by fwenzel** [mozilla/contribute.json#21]
Not entirely clear here (examples would help, maybe?) what one would do as a site owner to make this happen. Put it into contribute.json at the root of the site when it's deployed (what about projects that aren't deployed)? Or into the repository root?

**Comment by djmitche** [comment]
It'd be great to see this updated.  I'm adding contribute.json files to all of the relengapi-related repos (https://github.com/mozilla/build-relengapi/pull/226) but I'm not sure how to make them discoverable..

**Comment by pmclanahan** [comment]
A file named `contribute.json` at the root of the repo. If it's a website and you want web-based tools to also find it then serve it up as `/contribute.json` as well.

**Comment by peterbe** [comment]
@pmclanahan That lovely short sentence you just wrote is what this issue is all about. We should make a new page just for that.
