### ISSUE TITLE
Site not good on mobile

### ISSUE THREAD

**Issue by peterbe** [mozilla/contribute.json#51]
![img_4052](https://cloud.githubusercontent.com/assets/26739/6132729/6ba13446-b109-11e4-8db0-dfdf3798457e.PNG)
This is what it looks like if you pinch-zoom-out all the way.

CC @schalkneethling @craigcook @Osmose

**Comment by schalkneethling** [comment]
bleh, that can be fixed. Which device was that, just for interest sake.

**Comment by schalkneethling** [comment]
I know why btw, some is sandstone styles kicking in and the others are things added that is not part of it, so it does not play nicely together. And of course, we never tested it on mobile :(

**Comment by peterbe** [comment]
> bleh, that can be fixed. Which device was that, just for interest sake.

My iPhone's Safari
