### ISSUE TITLE
Examples of Use page broken

### ISSUE THREAD

**Issue by peterbe** [mozilla/contribute.json#56]
[This comment](https://github.com/mozilla/contribute.json/commit/e516a4e42248dc90063e6b3ba3a58317781e5cc0) broke the "Examples of Use" page. (thank you git bisect!)
cc @koddsson 

At the time of writing you can see the problem on https://contribute.paas.allizom.org/examples
Something to do with the overflow I guess. 
cc @schalkneethling

**Comment by koddsson** [comment]
Whoops. I think I have a fix for this @peterbe. I'm gonna confirm and hit you back with a PR in a minute.

**Comment by peterbe** [comment]
Cool. Looking forward to it.
