### ISSUE TITLE
Validator doesn't match Mozilla security guidelines

### ISSUE THREAD

**Issue by markrcote** [mozilla/contribute.json#78]
According to https://wiki.mozilla.org/Security/Guidelines/Web_Security#contribute.json, the "urls" attribute is required. However, the schema that is validated at contributejson.org doesn't list that as required, so the HTTP Observatory won't give you the points for a contribute.json that is ruled valid here.

**Comment by markrcote** [comment]
Also, "bugs, participate (particularly irc and irc-contacts)" are required by the security guidelines.

**Comment by peterbe** [comment]
IMHO the `bugs` key should not be required. Not all projects have a URL(s) since they might not necessarily result in a viewable website. 

I think the Web Security guidelines are incorrect.

**Comment by peterbe** [comment]
What do you think @april?

**Comment by april** [comment]
The `contribute.json` test is not validating that the the file is valid as defined by contributejson.org. Instead, it is validating that there is information contained therein that allows the Mozilla InfoSec team to quickly triage bugs particularly for websites were they/we might not have any contact information.

**Comment by peterbe** [comment]
Therein, it's Mozilla InfoSec's "addition" and nothing "wrong" with the schema here. Ok with that @markrcote ?

**Comment by markrcote** [comment]
Okay, but the wiki should be clearer then. In particular, there's a link to the standard but no clear statement that the security guidelines are a superset of the contribute.json standard.

I can make this wiki update if no one minds, just to save anyone the confusion I had.

**Comment by april** [comment]
The Web Security guidelines seem clear to me, but I'll happily accept revisions that make things even clearer.  :)

https://github.com/mozilla/wikimo_content

Is where it's kept.  Thanks!
